### ISSUE TITLE
not an issue but

### ISSUE THREAD

**Issue by arceuss** [sdelgadoc/download-tweets-ai-text-gen-plus#1]
what does (number)it mean

**Comment by sdelgadoc** [comment]
Can you tell me where you found a reference to "(number)it" and I'll take a look?  I'm not sure what it is.

**Comment by arceuss** [comment]
Oldest Tweet: 2020-06-06 07:33:14: : 2880it [1:13:47,  1.54s/it]

**Comment by sdelgadoc** [comment]
2880it: 2,880 iterations performed (an iteration is a tweet)
1:13:47: 1 hour, 13 minutes, 47 seconds of execution
1.54s/it: 1.54 seconds per iteration (tweet)

**Comment by arceuss** [comment]
ah ok
