### ISSUE TITLE
No module named 'keys'

### ISSUE THREAD

**Issue by burritosoftware** [sdelgadoc/download-tweets-ai-text-gen-plus#4]
Currently having an issue running this on my Ubuntu server.

```py
Traceback (most recent call last):
  File "download_tweets.py", line 11, in <module>
    from keys import keys
ModuleNotFoundError: No module named 'keys'
```

**Comment by sdelgadoc** [comment]
What's happening is that the `download_tweets.py` file can't find the `keys.py` file, which should be in the same folder.

To fix, first check that you have the `keys.py` file in the same folder as the `download_tweets.py` folder.  If you don't have it, re-clone the repo to get it.

If you do have it, make sure you are running python from the same folder as the `download_tweets.py` so it can find the missing file.

Try those two things and let me know.
