### ISSUE TITLE
Line 1 column 1 error

### ISSUE THREAD

**Issue by Owasgwi** [sdelgadoc/download-tweets-ai-text-gen-plus#5]
I have this issue retrieving tweets from user DrOakley1689.
![9-18-2020_issue](https://user-images.githubusercontent.com/51683127/93636264-77536f00-f9a8-11ea-92c3-004ada294588.PNG)

**Comment by sdelgadoc** [comment]
Unfortunately, it looks like that specific account is one that, for one of multiple reasons, Twitter doesn't allow you to scrape.

You can reproduce the issue with this simple script that uses the twint library directly.

```python
import twint

username = "@DrOakley1689"
c = twint.Config()
c.Username = username

twint.run.Search(c)
```

**Comment by Owasgwi** [comment]
Sorry, I've tried three more accounts and get the same error.

![9-18-2020_issue2](https://user-images.githubusercontent.com/51683127/93656071-7fc59d00-f9dc-11ea-9445-b6471e154813.PNG)

**Comment by sdelgadoc** [comment]
Similarly to what you are seeing, I was able to reproduce the issue with a number of other accounts, and have not been able to find an account that doesn't generate the error.

It looks like it's an issue with the twint scrapping library and that other folks are experiencing it, as referenced in this issue (https://github.com/twintproject/twint/issues/915).

Once the twint team fixes the issue, this script should start working correctly.

**Comment by Owasgwi** [comment]
I followed the directions to uninstall and re-install twint (https://github.com/twintproject/twint/issues/915#issuecomment-716196991),

and am now getting this error. 

![10-26-2020_issue3](https://user-images.githubusercontent.com/51683127/97252572-8b6c6680-17c7-11eb-8337-7a97f4fd2881.PNG)

**Comment by sdelgadoc** [comment]
Sorry for the delay.  Twitter appears to be making it more difficult for scraping tools to collect information.  I think it's likely that they will continue to make it difficult moving forward.

If I were to port this script to use the Twitter API, which you can access by applying for a Twitter App, would you still find it useful?

**Comment by Owasgwi** [comment]
Thank you for replying. I wouldn't, because I have deactivated my Twitter account and wouldn't open a new account.
