### ISSUE TITLE
Forbidden: Authentication succeeded but account is not authorized to access this resource.

### ISSUE THREAD

**Issue by murAIda** [sdelgadoc/download-tweets-ai-text-gen-plus#9]
Did you experienced that? I followed all Your steps, as Twitter dev account, keys obtaing, environment label setting, anyway I am getting next errors:

**tweepy.error.TweepError: {'message': 'Forbidden: Authentication succeeded but account is not authorized to access this resource.', 'sent': '2021-01-29T23:24:30+00:00', 'transtweepy.error.TweepError: {'message': 'Forbidden: AuthactionId': '007a928300d578e4'}
Oldest Tweet:   0%|**

Do you have some advice?

**Comment by sdelgadoc** [comment]
Thanks for using the repo!  The error says that you authenticated correctly, so your keys are working.  However, it looks like you either don't have a development environment set up, or the development environment's name is entered incorrectly.

To create a development environment, go to the Twitter API's [Dev environments page](https://developer.twitter.com/en/account/environments), generate a Dev environment for the Full Archive API, and input the environment's name into the section of the `keys.py` file shown below.

```py
environment_name = ""
```

Let me know if that works.

**Comment by murAIda** [comment]
Thanks, after checking Dev environments page I found, there are 3 types of environment and I initiate 
**Search Tweets: 30-DaysSandbox**, which did not work,  but  after selection **Search Tweets: Full ArchiveSandbox**,  the process started work fine.
